#!/bin/bash

# Reboot webserver and chrome instance for a Raspberry Pi.

# Starting message.
echo "$(date): Booting homehub for Raspberry Pi"

# Crash on any errors
set -e

# Change to correct directory
SCRIPT_PATH="`dirname \"$0\"`"
echo "$(date): changing to directory: $SCRIPT_PATH"
cd "$SCRIPT_PATH"

# Wait for network connection
tryct=0
maxtryct=100
while ! ifconfig | grep "192.168." > /dev/null; do
    tryct=$((tryct+1))
    if ((tryct > maxtryct)); then
        echo "$(date): giving up"
        exit 1
    fi
    echo "$(date): Waiting for network connection (Attempt $tryct out of $maxtryct)..."
    sleep 3
done

# Push notification if IPv4 has updated
../env/bin/python manage.py send_ip_update_alert

# Set hubstate to isactive field to true
../env/bin/python manage.py set_hubstate_isactive_to_true

# Pull Source Code
git pull

# Update Dependancies
../env/bin/pip install -r ../requirements.txt

# Build Angular Assets
cd website/appclient
# npm install
npm run-script buildprod
cd ..
cd ..

# Start gunicorn server
nohup gunicorn --bind 127.0.0.1:8000 --workers 1 homehub.wsgi & disown

# Open Google Chrome
nohup google-chrome http://localhost:8000 --start-fullscreen > /dev/null & disown

# Ending message.
echo "$(date): Boot Sequence Complete"
