#!/bin/bash

# Reboot webserver and chrome instance for a Raspberry Pi.

# Starting message.
echo "$(date): Booting homehub for Raspberry Pi"

# Kill any gunicorn processes running
kill $(ps -e | grep gunicorn | awk '{print $1}')


# Change to correct directory
SCRIPT_PATH="`dirname \"$0\"`"
echo "$(date): changing to directory: $SCRIPT_PATH"
cd "$SCRIPT_PATH"

sleep 5

# # Wait for network connection
# tryct=0
# maxtryct=100
# while true; do
#     python3.6 /home/pi/check_connection.py
#     if [ $? -eq 0 ]; then
#     echo "found network connection"
#         break
#     fi

#     tryct=$((tryct+1))
#     if ((tryct > maxtryct)); then
#         echo "$(date): giving up"
#         exit 1
#     fi
#     echo "$(date): Waiting for network connection (Attempt $tryct out of $maxtryct)..."
#     sleep 3
# done


# Crash on any errors
set -e

# Push notification if IPv4 has updated
../env/bin/python manage.py send_ip_update_alert

# Set hubstate to isactive field to true
../env/bin/python manage.py set_hubstate_isactive_to_true

# Start gunicorn server
source ../env/bin/activate && nohup gunicorn --bind 0.0.0.0:8000 --workers 1 homehub.wsgi & disown

# Open Google Chrome
DISPLAY=:0 chromium-browser --app=http://localhost:8000 --kiosk --start-fullscreen > /dev/null

