# Generated by Django 3.2 on 2021-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersource',
            name='name',
            field=models.CharField(default='New York City', max_length=30),
            preserve_default=False,
        ),
    ]
