# Generated by Django 3.2 on 2021-04-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weathersource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='name',
            field=models.CharField(default='derp', max_length=30),
            preserve_default=False,
        ),
    ]
